# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9fa13e17864aa2afa515937aef56bc344da08ff6c94250a7de40389a860e2a39885a9d8ba55b73d541ba179eab1307cbb9094e79096a7489b1529a8f408c8624

test:
  secret_key_base: 92b8a672b350d5bab4136ccb3481d8308d47186e8136ff2e7fc270fa296cd82d27eb370f5793978fe7253316e6900301716506263a4b1409b6de4cbaf9f4e80b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
